### PR TITLE
Add set up instructions for MacOS

### PR DESCRIPTION
**Pull request by ocsmit**

### CODE REVIEW

**Review by chaedri — APPROVED** [review]
Looks great to me! Thanks @ocsmit

**Comment by ocsmit** [comment]
see #22 for grass set up determined by the operating system of the user

**Review by wenzeslaus — CHANGES_REQUESTED** [review]
Looks good to me in general. Thank you. I think this is "whatever gets us there is fine" situation, but I have some comments and some would be nice to address.

The note says "...setup was completed with...compiled with [grass-conda](https://github.com/nilason/grass-conda)". I think the [recommended version available for download](http://grassmac.wikidot.com/downloads) is just that and it will work, so maybe say "it will/should work with the [GRASS GIS for the Mac](http://grassmac.wikidot.com/) version" or something like that.

I have seen recommendations for using `python3 -m pip install jupyterlab` instead of `pip3 install jupyterlab`. I personally find the pip3 version simpler, but the python3 version is clear about what Python is used.

Given the multiple versions of Python, a recommendation on starting the JupyterLab would be nice as Step 3.

I wonder whether we need Step 2. The code in the _Start_ section takes care of that. The Bash version would be advantageous if Jupyter is started from the Terminal with PATH set (if that works). I'm putting this up for consideration. Having both executable path and Python path resolved in the notebook makes sense to me. Anyway, this is what I do on my computer (to get my development version of GRASS GIS instead of the system one which is on path):

```
PATH=/home/vpetras/.../grass/bin.x86_64-pc-linux-gnu/:$PATH jupyter lab
```

At the end it says, "It may be useful to copy the paths from Step 7 somewhere" but I don't see Step 7, perhaps just refer to the _Start_ section.

It is unclear to me what will be the order returned by Path.glob, but this let's say this is not an issue since most people will have only one version and you print the version used. (No action needed here.)

As far as I understand, `str()` is not needed in `print(f"Using GRASS located @ {str(grass_call)}")`. `{grass_class!s}` would be a better way to write it (possibly also faster), but since that's the [default](https://docs.python.org/3/library/string.html#format-specification-mini-language), it can be omitted.

**Comment by ocsmit** [comment]
I believe most, if not all of your comments should be addressed in the two recent commits. Let me know if I missed something!

**Review by wenzeslaus — APPROVED** [review]
This looks great! Let's merge it.

**Pull request merged**
